### ISSUE TITLE
Notation des matrices en 2.4.1

### ISSUE THREAD

**Issue by StanIsAdmin** [TheoVerhelst/Resume-INFO-F-310#1]
En 2.4.1 tu devrais utiliser des majuscules pour dénommer tes matrices, et corriger l'abus de notation `x >= 0` en `x >= 0 \forall x \in X`

**Comment by StanIsAdmin** [comment]
Je soutiens l'utilisation des majuscules car les vecteurs sont aussi des matrices, de plus tu utilises la lettre `b` un peu plus bas, pour désigner l'équivalent d'un élément du premier `b`.

**Comment by TheoVerhelst** [comment]
La notation que j'utilise c'est une majuscule pour les matrices, et une minuscule pour les vecteurs. Vu qu'on utilise plus souvent des vecteurs que des scalaires, ça permet d'avoir une idée de la dimension de ce qu'on voit.

**Comment by StanIsAdmin** [comment]
Dans ce cas tu devrais utiliser des lettres différentes pour désigner tes scalaires, quand tu te trouves dans la même section au moins.

**Comment by TheoVerhelst** [comment]
Ah oui plus bas j'utilise a et b, mais c'est une petite propriété arithmétique, sans rapport avec le vecteur b. Je vais changer ça.
